apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - image: ifilyaninitmo/itdt-contained-frontend:master
          name: react-app
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_USERNAME
              value: colorblind
            - name: REACT_APP_COMPANY_NAME
              value: Yandex
